# Generated by Django 2.1.7 on 2019-03-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.FloatField()),
                ('salario_ex', models.FloatField()),
            ],
        ),
    ]
